# Generated by Django 5.0.6 on 2024-07-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_code',
            field=models.TextField(blank=True),
        ),
    ]
